CATEGORIES = {
    "vnexpress": {
        "Chính trị": "https://vnexpress.net/thoi-su/chinh-tri",
        "Nhân sự": "https://vnexpress.net/thoi-su/chinh-tri/nhan-su",
        "Kỷ nguyên mới": "https://vnexpress.net/thoi-su/huong-toi-ky-nguyen-moi",
        "Dân sinh": "https://vnexpress.net/thoi-su/dan-sinh",
        "Việc làm": "https://vnexpress.net/thoi-su/lao-dong-viec-lam",
        "Giao thông": "https://vnexpress.net/thoi-su/giao-thong",
        "Mekong": "https://vnexpress.net/thoi-su/mekong",
        "Quỹ Hy vọng": "https://vnexpress.net/thoi-su/quy-hy-vong",
        "Tư liệu": "https://vnexpress.net/the-gioi/tu-lieu",
        "Phân tích": "https://vnexpress.net/the-gioi/phan-tich",
        "Người Việt 5 châu": "https://vnexpress.net/the-gioi/nguoi-viet-5-chau",
        "Cuộc sống đó đây": "https://vnexpress.net/the-gioi/cuoc-song-do-day",
        "Quân sự": "https://vnexpress.net/the-gioi/quan-su",
        "AI": "https://vnexpress.net/cong-nghe/ai",
        "Chuyển đổi số": "https://vnexpress.net/cong-nghe/chuyen-doi-so",
        "Nhịp sống số": "https://vnexpress.net/cong-nghe/nhip-song-so",
        "Thiết bị": "https://vnexpress.net/cong-nghe/thiet-bi",
        "Trải nghiệm": "https://vnexpress.net/cong-nghe/trai-nghiem",
        "GameVerse 2025": "https://vnexpress.net/cong-nghe/vgv-2025",
        "Tin tức": "https://vnexpress.net/giao-duc/tin-tuc",
        "Đổi mới sáng tạo": "https://vnexpress.net/khoa-hoc/doi-moi-sang-tao",
        "Bàn tròn": "https://vnexpress.net/khoa-hoc/ban-tron",
        "Nhân vật": "https://vnexpress.net/khoa-hoc/nhan-vat",
        "Cửa sổ tri thức": "https://vnexpress.net/khoa-hoc/cua-so-tri-thuc",
        "Thế giới tự nhiên": "https://vnexpress.net/khoa-hoc/the-gioi-tu-nhien",
        "Vũ trụ": "https://vnexpress.net/khoa-hoc/vu-tru",
        "Sáng kiến khoa học 2025": "https://vnexpress.net/khoa-hoc/cuoc-thi-sang-kien-khoa-hoc",
        "Bình luận nhiều": "https://vnexpress.net/goc-nhin/binh-luan-nhieu",
        "Chính trị & chính sách": "https://vnexpress.net/goc-nhin/chinh-tri-chinh-sach",
        "Y tế & sức khỏe": "https://vnexpress.net/goc-nhin/y-te-suc-khoe",
        "Kinh doanh & quản trị": "https://vnexpress.net/goc-nhin/kinh-doanh-quan-tri",
        "Giáo dục & tri thức": "https://vnexpress.net/goc-nhin/giao-duc-tri-thuc",
        "Môi trường": "https://vnexpress.net/goc-nhin/moi-truong",
        "Văn hóa & lối sống": "https://vnexpress.net/goc-nhin/van-hoa-loi-song",
        "Covid 19": "https://vnexpress.net/goc-nhin/covid-19",
        "Chính sách": "https://vnexpress.net/bat-dong-san/chinh-sach",
        "Thị trường": "https://vnexpress.net/oto-xe-may/thi-truong",
        "Dự án": "https://vnexpress.net/bat-dong-san/du-an",
        "Không gian sống": "https://vnexpress.net/bat-dong-san/khong-gian-song",
        "Tư vấn": "https://vnexpress.net/du-lich/tu-van",
        "Các bệnh": "https://vnexpress.net/suc-khoe/cac-benh",
        "Sống khỏe": "https://vnexpress.net/suc-khoe/song-khoe",
        "Vaccine": "https://vnexpress.net/suc-khoe/vaccine",
        "Marathon": "https://vnexpress.net/the-thao/marathon",
        "Tennis": "https://vnexpress.net/the-thao/tennis",
        "Các môn khác": "https://vnexpress.net/the-thao/cac-mon-khac",
        "Hậu trường": "https://vnexpress.net/the-thao/hau-truong",
        "Giới sao": "https://vnexpress.net/giai-tri/gioi-sao",
        "Sách": "https://vnexpress.net/giai-tri/sach",
        "Phim": "https://vnexpress.net/giai-tri/phim",
        "Nhạc": "https://vnexpress.net/giai-tri/nhac",
        "Làm đẹp": "https://vnexpress.net/giai-tri/lam-dep",
        "Sân khấu - Mỹ thuật": "https://vnexpress.net/giai-tri/san-khau-my-thuat",
        "Hồ sơ phá án": "https://vnexpress.net/phap-luat/ho-so-pha-an",
        "Video": "https://vnexpress.net/phap-luat/video",
        "Tuyển sinh": "https://vnexpress.net/giao-duc/tuyen-sinh",
        "Chân dung": "https://vnexpress.net/giao-duc/chan-dung",
        "Du học": "https://vnexpress.net/giao-duc/du-hoc",
        "Thảo luận": "https://vnexpress.net/giao-duc/thao-luan",
        "Học tiếng Anh": "https://vnexpress.net/giao-duc/hoc-tieng-anh",
        "Giáo dục 4.0": "https://vnexpress.net/giao-duc/giao-duc-40",
        "Thời sự": "https://vnexpress.net/y-kien/thoi-su"
    },
    "tuoitre": {
        "Trang chủ": "https://tuoitre.vn/rss/tin-moi-nhat.rss",
        "Thời sự": "https://tuoitre.vn/rss/thoi-su.rss",
        "Thế giới": "https://tuoitre.vn/rss/the-gioi.rss",
        "Pháp luật": "https://tuoitre.vn/rss/phap-luat.rss",
        "Kinh doanh": "https://tuoitre.vn/rss/kinh-doanh.rss",
        "Công nghệ": "https://tuoitre.vn/rss/nhip-song-so.rss",
        "Xe": "https://tuoitre.vn/rss/xe.rss",
        "Nhịp sống trẻ": "https://tuoitre.vn/rss/nhip-song-tre.rss",
        "Văn hóa": "https://tuoitre.vn/rss/van-hoa.rss",
        "Giải trí": "https://tuoitre.vn/rss/giai-tri.rss",
        "Thể thao": "https://tuoitre.vn/rss/the-thao.rss",
        "Giáo dục": "https://tuoitre.vn/rss/giao-duc.rss",
        "Khoa học": "https://tuoitre.vn/rss/khoa-hoc.rss",
        "Sức khỏe": "https://tuoitre.vn/rss/suc-khoe.rss",
        "Giả thật": "https://tuoitre.vn/rss/gia-that.rss",
        "Thư giãn": "https://tuoitre.vn/rss/thu-gian.rss",
        "Bạn đọc": "https://tuoitre.vn/rss/ban-doc.rss",
        "Du lịch": "https://tuoitre.vn/rss/du-lich.rss"
    },
    "baodanang": {
        "Chính trị": "https://baodanang.vn/chinhtrixahoi/",
        "Xã hội": "https://baodanang.vn/xa-hoi/",
        "Kinh tế": "https://baodanang.vn/kinhte/",
        "Giáo dục": "https://baodanang.vn/channel/5411/",
        "Quốc tế": "https://baodanang.vn/channel/5408/",
        "Văn hóa - Giải trí": "https://baodanang.vn/channel/5414/",
        "Y tế - Sức khỏe": "https://baodanang.vn/ytesuckhoe/",
        "Pháp luật": "https://baodanang.vn/channel/5432/",
        "Thể thao": "https://baodanang.vn/channel/5422/"
    }
}