"""Add col category and source to articles

Revision ID: 3f53daf161d9
Revises: 567a62fc99fd
Create Date: 2025-05-26 11:05:48.004282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f53daf161d9'
down_revision: Union[str, None] = '567a62fc99fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('category', sa.String(length=512), nullable=True))
    op.add_column('articles', sa.Column('source', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'source')
    op.drop_column('articles', 'category')
    # ### end Alembic commands ###
