"""add crawl_log table

Revision ID: 55e4d9fc55bc
Revises: 9e212fb80e0f
Create Date: 2025-05-19 14:52:10.062364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e4d9fc55bc'
down_revision: Union[str, None] = '9e212fb80e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_log',
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('last_crawled', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crawl_log')
    # ### end Alembic commands ###
