"""delete col content in Article

Revision ID: 567a62fc99fd
Revises: 55e4d9fc55bc
Create Date: 2025-05-19 16:24:41.341970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567a62fc99fd'
down_revision: Union[str, None] = '55e4d9fc55bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
